version: 1.0.{build}
image: Visual Studio 2022

environment:
  nodejs_version: "18"

clone_folder: C:\projects\excel-electron-app

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - ps: New-Item -ItemType Directory -Force -Path "$env:APPDATA\npm"
  - npm run build

build: off  # ❗ отключаем msbuild, т.к. у нас не C++/C#

artifacts:
  - path: dist\*.exe
    name: installer
  - path: dist\*.zip
    name: portable
  - path: dist\**\*  # на случай, если exe лежит в подпапке